name: Update list
on:
  schedule:
  - cron: 30 1 * * *
jobs:
  awesome-stars:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install starred
    - name: Update repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: starred --username wilsonzlin --repository awesome-stars --sort --token ${GITHUB_TOKEN} --message '[GA] Update list'
